package com.glia.widgets.fcm

import com.google.firebase.messaging.RemoteMessage

/**
 * Interface for push notifications handling.
 *
 * This interface is used to handle push notifications in the Glia SDK.
 *
 * @see [GliaFcmService]
 */
interface PushNotifications {

    /**
     * This method should be called when a new token is generated by the Firebase Cloud Messaging framework.
     *
     * You should use this method only if you have your own FCM service.
     *
     * @see GliaFcmService
     *
     * @param newFcmToken New FCM token
     */
    fun updateFcmToken(newFcmToken: String?)

    /**
     * Should be called when a new remote message is received from the Firebase Cloud Messaging framework.
     *
     * You should use this method only if you have your own FCM service.
     *
     * @see GliaFcmService
     *
     * @param message - New FCM message
     */
    fun onNewMessage(message: RemoteMessage)
}

/**
 * @hide
 */
class PushNotificationsImpl(
    private val pushNotifications: com.glia.androidsdk.fcm.PushNotifications
) : PushNotifications {

    override fun updateFcmToken(newFcmToken: String?) {
        pushNotifications.updateFcmToken(newFcmToken)
    }

    override fun onNewMessage(message: RemoteMessage) {
        pushNotifications.onNewMessage(message)
    }
}
